### PR TITLE
fix: update alert policies one at a time because (concurrent updates are not supported)

### LINKED ISSUE #506: The test for samples/alerts.js fails due to "too many concurrent updates."
#### Environment details

  - OS: Debian GNU/Linux 10 (buster)
  - Node.js version: 10.14.2
  - npm version: 6.14.8
  - `@google-cloud/monitoring` version:

#### Steps to reproduce

  1. Download the googleapis/nodejs-monitoring library to a Google cloud shell.
  2. Run `npm run samples-test`.

### PR DESCRIPTION
**Pull request by syedashrafulla**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-monitoring/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [N/A] Appropriate docs were updated (if necessary)

Fixes #506 🦕

### CODE REVIEW

**Comment by bcoe** [comment]
@syedashrafulla it looks like there are a couple linting issues to address, I kicked off the integration tests so you can see if things are working.

**Comment by syedashrafulla** [comment]
@bcoe apologies about that, lint should now be cleaned.

**Comment by syedashrafulla** [comment]
I think all that's missing is now a review, but let me know if I should run a test.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@syedashrafulla thank you for the contribution.

**Pull request merged**
