### PR TITLE
docs(samples): cleanup quickstart and metrics samples 

### PR DESCRIPTION
**Pull request by bcoe**
Fixes quickstart and metrics samples to run with any optional parameters truly optional and using best practices.

Refs: https://github.com/googleapis/nodejs-monitoring/pull/443

### CODE REVIEW

**Comment by bcoe** [comment]
@syedashrafulla I ended up needing to create a new branch to update linting on #443. Thank you very much for the contribution.

**Review by JustinBeckwith — APPROVED** [review]

**Comment by bcoe** [comment]
@syedashrafulla this refactor appears to break our integration tests:

https://source.cloud.google.com/results/invocations/dafe301e-6659-4469-bd18-5a521f90a343/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-monitoring%2Fnode12%2Fsamples-test/log

It seems like setting the values:

```
        location: 'us-east1-a',
        namespace: 'default',
        job: 'daily',
        task_id: '1',
```

Is potentially too specific to your use case. thoughts?

**Comment by syedashrafulla** [comment]
Sounds good, @bcoe! I'll fix the integration tests and/or the pull request and then ask for a re-review.

**Comment by bcoe** [comment]
@syedashrafulla 👍 I'll close this and wait on your PR, sorry for screwing things up during the merge. I'll make sure to run the integration tests on your PR this time too, to give feedback.

**Pull request closed without merging**
