### PR TITLE
Release @google-cloud/monitoring v0.6.0

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by busunkim96** [comment]
@JustinBeckwith Autorelease is having trouble releasing this. I *think* it's because because [release v0.6.0 already exists](https://github.com/googleapis/nodejs-monitoring/releases).

**Comment by JustinBeckwith** [comment]
wooooooah.

**Comment by JustinBeckwith** [comment]
I chose 0.6 because it's what releasetool gave me after selecting *minor*.  It looks like some kind of bug with ordering.  Check this out:
https://github.com/googleapis/nodejs-monitoring/releases

For some reason 0.5.1 shows up ahead of 0.6.  Weird.

**Comment by busunkim96** [comment]
I think the releases page shows the most recent release first.  It looks like @kinwa91 made patch release 0.5.1 after 0.6.0. Releasetool also assumes the most recent release is what it should increment on.  I'll file a bug on releasetool to get `releasetool start` to do something more sensible. 

Could you remove the `autorelease: pending` label so Autorelease stops trying to release this? :smile:

**Pull request merged**
